
export const currencyOptions = [
    { code: 'USD', name: 'United States Dollar', symbol: '$', flag: 'https://upload.wikimedia.org/wikipedia/en/a/a4/Flag_of_the_United_States.svg' },
    { code: 'EUR', name: 'Euro', symbol: '€', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b7/Flag_of_Europe.svg' },
    { code: 'JPY', name: 'Japanese Yen', symbol: '¥', flag: 'https://upload.wikimedia.org/wikipedia/en/9/9e/Flag_of_Japan.svg' },
    { code: 'GBP', name: 'British Pound', symbol: '£', flag: 'https://upload.wikimedia.org/wikipedia/en/a/ae/Flag_of_the_United_Kingdom.svg' },
    { code: 'AUD', name: 'Australian Dollar', symbol: 'A$', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b9/Flag_of_Australia.svg' },
    { code: 'CAD', name: 'Canadian Dollar', symbol: 'C$', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cf/Flag_of_Canada.svg' },
    { code: 'CHF', name: 'Swiss Franc', symbol: 'CHF', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/f3/Flag_of_Switzerland.svg' },
    { code: 'CNY', name: 'Chinese Yuan', symbol: '¥', flag: 'https://upload.wikimedia.org/wikipedia/commons/2/21/Flag_of_the_People%27s_Republic_of_China.svg' },
    { code: 'SEK', name: 'Swedish Krona', symbol: 'kr', flag: 'https://upload.wikimedia.org/wikipedia/en/4/4c/Flag_of_Sweden.svg' },
    { code: 'NZD', name: 'New Zealand Dollar', symbol: 'NZ$', flag: 'https://upload.wikimedia.org/wikipedia/commons/3/3e/Flag_of_New_Zealand.svg' },
    { code: 'MXN', name: 'Mexican Peso', symbol: '$', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fc/Flag_of_Mexico.svg' },
    { code: 'SGD', name: 'Singapore Dollar', symbol: 'S$', flag: 'https://upload.wikimedia.org/wikipedia/commons/4/48/Flag_of_Singapore.svg' },
    { code: 'HKD', name: 'Hong Kong Dollar', symbol: 'HK$', flag: 'https://upload.wikimedia.org/wikipedia/commons/5/5b/Flag_of_Hong_Kong.svg' },
    { code: 'NOK', name: 'Norwegian Krone', symbol: 'kr', flag: 'https://upload.wikimedia.org/wikipedia/commons/d/d9/Flag_of_Norway.svg' },
    { code: 'KRW', name: 'South Korean Won', symbol: '₩', flag: 'https://upload.wikimedia.org/wikipedia/commons/0/09/Flag_of_South_Korea.svg' },
    { code: 'TRY', name: 'Turkish Lira', symbol: '₺', flag: 'https://upload.wikimedia.org/wikipedia/commons/b/b4/Flag_of_Turkey.svg' },
    { code: 'RUB', name: 'Russian Ruble', symbol: '₽', flag: 'https://upload.wikimedia.org/wikipedia/en/f/f3/Flag_of_Russia.svg' },
    { code: 'INR', name: 'Indian Rupee', symbol: '₹', flag: 'https://upload.wikimedia.org/wikipedia/en/4/41/Flag_of_India.svg' },
    { code: 'BRL', name: 'Brazilian Real', symbol: 'R$', flag: 'https://upload.wikimedia.org/wikipedia/en/0/05/Flag_of_Brazil.svg' },
    { code: 'ZAR', name: 'South African Rand', symbol: 'R', flag: 'https://upload.wikimedia.org/wikipedia/commons/a/af/Flag_of_South_Africa.svg' },
    { code: 'ARS', name: 'Argentine Peso', symbol: '$', flag: 'https://upload.wikimedia.org/wikipedia/commons/1/1a/Flag_of_Argentina.svg' },
    { code: 'THB', name: 'Thai Baht', symbol: '฿', flag: 'https://upload.wikimedia.org/wikipedia/commons/a/a9/Flag_of_Thailand.svg' },
    { code: 'MYR', name: 'Malaysian Ringgit', symbol: 'RM', flag: 'https://upload.wikimedia.org/wikipedia/commons/6/66/Flag_of_Malaysia.svg' },
    { code: 'IDR', name: 'Indonesian Rupiah', symbol: 'Rp', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9f/Flag_of_Indonesia.svg' },
    { code: 'PHP', name: 'Philippine Peso', symbol: '₱', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Flag_of_the_Philippines.svg' },
    { code: 'PLN', name: 'Polish Zloty', symbol: 'zł', flag: 'https://upload.wikimedia.org/wikipedia/en/1/12/Flag_of_Poland.svg' },
    { code: 'HUF', name: 'Hungarian Forint', symbol: 'Ft', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/c1/Flag_of_Hungary.svg' },
    { code: 'CZK', name: 'Czech Koruna', symbol: 'Kč', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_Czech_Republic.svg' },
    { code: 'DKK', name: 'Danish Krone', symbol: 'kr', flag: 'https://upload.wikimedia.org/wikipedia/commons/9/9c/Flag_of_Denmark.svg' },
    { code: 'NGN', name: 'Nigerian Naira', symbol: '₦', flag: 'https://upload.wikimedia.org/wikipedia/commons/7/79/Flag_of_Nigeria.svg' },
    { code: 'EGP', name: 'Egyptian Pound', symbol: '£', flag: 'https://upload.wikimedia.org/wikipedia/commons/f/fe/Flag_of_Egypt.svg' },
    { code: 'AED', name: 'United Arab Emirates Dirham', symbol: 'د.إ', flag: 'https://upload.wikimedia.org/wikipedia/commons/c/cb/Flag_of_the_United_Arab_Emirates.svg' },
];

export const fixedAmounts = {
    USD: 100,
    EUR: 85,
    JPY: 11000,
    GBP: 75,
    AUD: 130,
    CAD: 125,
    INR: 7500,
    CNY: 650,
  };